AllCops:
  Include:
    - '**/Gemfile'
    - lib/**/*
    - spec/**/*
    - gemirro.gemspec
  Exclude:
    - files/**/*
    - templates/**/*
    - etc/**/*
Metrics/MethodLength:
  Exclude:
    - lib/**/*
    - test/**/*.rb
    - spec/**/*.rb
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/LineLength:
  Exclude:
    - test/**/*
Metrics/ParameterLists:
  Enabled: false
Metrics/CyclomaticComplexity:
  Severity: warning
  Max: 20
Metrics/PerceivedComplexity:
  Severity: warning
  Max: 20
Lint/Eval:
  Enabled: false
Metrics/BlockNesting:
  Severity: warning
  Max: 4
Metrics/AbcSize:
  Enabled: false
Performance/StringReplacement:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/PredicateName:
  Exclude:
    - lib/fakefs/file.rb
Style/MethodName:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/TrivialAccessors:
  Enabled: true
  ExactNameMatch: true
