AllCops:
  DisplayCopNames: true
  Exclude:
    - files/**/*
    - templates/**/*
    - etc/**/*
    - vendor/**/*

Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/LineLength:
  Max: 120
  Exclude:
    - test/**/*
Metrics/ParameterLists:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

Lint/Eval:
  Enabled: false

Performance/StringReplacement:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false
Style/PredicateName:
  Exclude:
    - lib/fakefs/file.rb
Style/MethodName:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/TrivialAccessors:
  ExactNameMatch: true
Style/GuardClause:
  Enabled: false
Style/WordArray:
  Enabled: false
