language: ruby
sudo: false
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - jruby-1.7.27
  - jruby-9.1.17.0
  - jruby-head
env:
  matrix:
    - TASK=test
    - TASK=spec
matrix:
  allow_failures:
    - rvm: jruby-1.7.27
    - rvm: jruby-9.1.17.0
    - rvm: jruby-head
  include:
    - rvm: 2.3.7 # lowest from rvm list above
      env: TASK=rubocop

before_install: gem install bundler
script: bundle exec rake $TASK
