language: ruby
sudo: false
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - jruby-1.7.27
  - jruby-9.1.13.0
  - jruby-head
env:
  matrix:
    - TASK=test
    - TASK=spec
    - TASK=rubocop
matrix:
  allow_failures:
    - rvm: jruby-1.7.27
    - rvm: jruby-9.1.13.0
    - rvm: jruby-head
before_install:
  - gem --version
  - gem install bundler
script: bundle exec rake $TASK
